# Copia aquí tu URL de conexión a la base de datos de Render.
# Asegúrate de que siga el formato correcto.
# Ejemplo: DATABASE_URL="postgresql://usuario:contraseña@host:puerto/basededatos"

DATABASE_URL="postgresql://base_fjwm_user:herHQfSBfoUjEITVn33ePllUToGTsMVm@dpg-d46achshg0os73eesftg-a.oregon-postgres.render.com/base_fjwm"
